export default {
  M2: 'Principal lunar semidiurnal constituent',
  S2: 'Principal solar semidiurnal constituent',
  N2: 'Larger lunar elliptic semidiurnal constituent',
  K1: 'Lunar diurnal constituent',
  M4: 'Shallow water overtides of principal lunar constituent',
  O1: 'Lunar diurnal constituent',
  M6: 'Shallow water overtides of principal lunar constituent',
  MK3: 'Shallow water terdiurnal',
  S4: 'Shallow water overtides of principal solar constituent',
  MN4: 'Shallow water quarter diurnal constituent',
  NU2: 'Larger lunar evectional constituent',
  S6: 'Shallow water overtides of principal solar constituent',
  MU2: 'Variational constituent',
  '2N2': 'Lunar elliptical semidiurnal second-order constituent',
  OO1: 'Lunar diurnal',
  LAM2: 'Smaller lunar evectional constituent',
  S1: 'Solar diurnal constituent',
  M1: 'Smaller lunar elliptic diurnal constituent',
  J1: 'Smaller lunar elliptic diurnal constituent',
  MM: 'Lunar monthly constituent',
  SSA: 'Solar semiannual constituent',
  SA: 'Solar annual constituent',
  MSF: 'Lunisolar synodic fortnightly constituent',
  MF: 'Lunisolar fortnightly constituent',
  RHO: 'Larger lunar evectional diurnal constituent',
  Q1: 'Larger lunar elliptic diurnal constituent',
  T2: 'Larger solar elliptic constituent',
  R2: 'Smaller solar elliptic constituent',
  '2Q1': 'Larger elliptic diurnal',
  P1: 'Solar diurnal constituent',
  '2SM2': 'Shallow water semidiurnal constituent',
  M3: 'Lunar terdiurnal constituent',
  L2: 'Smaller lunar elliptic semidiurnal constituent',
  '2MK3': 'Shallow water terdiurnal constituent',
  K2: 'Lunisolar semidiurnal constituent',
  M8: 'Shallow water eighth diurnal constituent',
  MS4: 'Shallow water quarter diurnal constituent'
}
